# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        MainWindow.setMinimumSize(QtCore.QSize(450, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_OpenKey_d = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OpenKey_d.setStyleSheet("text-align: center;")
        self.lineEdit_OpenKey_d.setObjectName("lineEdit_OpenKey_d")
        self.horizontalLayout.addWidget(self.lineEdit_OpenKey_d)
        self.lineEdit_OpenKey_n = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OpenKey_n.setObjectName("lineEdit_OpenKey_n")
        self.horizontalLayout.addWidget(self.lineEdit_OpenKey_n)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_CloseKey_e = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CloseKey_e.setObjectName("lineEdit_CloseKey_e")
        self.horizontalLayout.addWidget(self.lineEdit_CloseKey_e)
        self.lineEdit_CloseKey_n = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CloseKey_n.setObjectName("lineEdit_CloseKey_n")
        self.horizontalLayout.addWidget(self.lineEdit_CloseKey_n)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Generate.setObjectName("pushButton_Generate")
        self.horizontalLayout_2.addWidget(self.pushButton_Generate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit_Massage = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Massage.setObjectName("textEdit_Massage")
        self.verticalLayout.addWidget(self.textEdit_Massage)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_Decipher = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Decipher.setObjectName("pushButton_Decipher")
        self.horizontalLayout_3.addWidget(self.pushButton_Decipher)
        self.pushButton_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Encrypt.setObjectName("pushButton_Encrypt")
        self.horizontalLayout_3.addWidget(self.pushButton_Encrypt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA_Encryption"))
        self.label.setText(_translate("MainWindow", "Открытый ключ:"))
        self.label_2.setText(_translate("MainWindow", "Закрытый ключ:"))
        self.pushButton_Generate.setText(_translate("MainWindow", "Сгенерировать рандомно"))
        self.pushButton_Decipher.setText(_translate("MainWindow", "Расшифровать"))
        self.pushButton_Encrypt.setText(_translate("MainWindow", "Зашифровать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
